// Interface automatically generated by schemas-to-ts

import { Blog } from '../../../api/blog/content-types/blog/blog';
import { Blog_Plain } from '../../../api/blog/content-types/blog/blog';

export interface RelatedArticles {
  blogs: { data: Blog[] };
  intro?: string;
}
export interface RelatedArticles_Plain {
  blogs: Blog_Plain[];
  intro?: string;
}

export interface RelatedArticles_NoRelations {
  blogs: number[];
  intro?: string;
}

