// Interface automatically generated by schemas-to-ts

import { SharedImage } from './SharedImage';
import { RelatedArticles } from './RelatedArticles';
import { SharedImage_Plain } from './SharedImage';
import { RelatedArticles_Plain } from './RelatedArticles';
import { SharedImage_NoRelations } from './SharedImage';
import { RelatedArticles_NoRelations } from './RelatedArticles';

export interface Seo {
  metaTitle: string;
  metaDescription: string;
  media?: SharedImage;
  preventIndexing: boolean;
  keywords: string;
  structuredData: any;
  articles?: RelatedArticles;
}
export interface Seo_Plain {
  metaTitle: string;
  metaDescription: string;
  media?: SharedImage_Plain;
  preventIndexing: boolean;
  keywords: string;
  structuredData: any;
  articles?: RelatedArticles_Plain;
}

export interface Seo_NoRelations {
  metaTitle: string;
  metaDescription: string;
  media?: SharedImage_NoRelations;
  preventIndexing: boolean;
  keywords: string;
  structuredData: any;
  articles?: RelatedArticles_NoRelations;
}

