// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface SharedImage {
  media?: { data: Media };
  alt: string;
}
export interface SharedImage_Plain {
  media?: Media_Plain;
  alt: string;
}

export interface SharedImage_NoRelations {
  media?: number;
  alt: string;
}

