// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Blog {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    subtitle?: string;
    heroImage?: { data: Media };
    heroImageDescription?: string;
    content?: string;
    slug: string;
    seo?: Seo;
    locale: string;
    localizations?: { data: Blog[] };
  };
}
export interface Blog_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  subtitle?: string;
  heroImage?: Media_Plain;
  heroImageDescription?: string;
  content?: string;
  slug: string;
  seo?: Seo_Plain;
  locale: string;
  localizations?: Blog_Plain[];
}

export interface Blog_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  subtitle?: string;
  heroImage?: number;
  heroImageDescription?: string;
  content?: string;
  slug: string;
  seo?: Seo_NoRelations;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  subtitle?: string;
  heroImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  heroImageDescription?: string;
  content?: string;
  slug: string;
  seo?: Seo_Plain;
  locale: string;
  localizations?: Blog[];
}
